### ISSUE TITLE
상품의 긍부정 키워드 조회

### ISSUE THREAD

**Issue by Kwon770** [review-mate/review-mate-be#19]

**Comment by hyeonjin25** [comment]
## API 요청
### 필요 api
속성 및 키워드 분류 데이터

### 데이터 형식
```
{
	"property": ["청결", "분위기"],
	"keyword": [
		["먼지", "냄새"],
		["모던", "클래식"]
	]
}
```

### 참고자료
> ![image](https://github.com/review-mate/review-mate-be/assets/65444249/dcbcb64c-fb09-4369-ac8f-971d709f153b)
