### ISSUE TITLE
[api issue] cors 오류

### ISSUE THREAD

**Issue by hyeonjin25** [review-mate/review-mate-be#55]
### 관련 기능
상품별 리뷰 목록 불러오기

### 요청 url
http://test.api.reviewmate.co.kr:8080/api/widget/v1/goodchoice.kr/products/HOTEL-0001/reviews?orderBy=LATEST&page=0&size=10

### 상황
같은 url로 postman을 사용하면 정상적으로 동작합니다, cors 오류로 브라우저에서 생긴 이슈인 것 같습니다

### 참고자료
> ![image](https://github.com/review-mate/review-mate-be/assets/65444249/e281fe38-d712-43a3-9efa-db3e244f5a1a)

>![image](https://github.com/review-mate/review-mate-be/assets/65444249/9e190639-6ace-4ef5-9d00-2f5230e7c012)

**Comment by Kwon770** [comment]
로컬 개발 환경을 지원하기 위해, #56 에서 임시적으로 CORS를 허용했어요.
