### ISSUE TITLE
리뷰 통계 관련 api

### ISSUE THREAD

**Issue by hyeonjin25** [review-mate/review-mate-be#59]
### 필요 api
리뷰 통계 관련 api
1. 총 리뷰 개수
2. 별점 평균
3. 평점 별 리뷰 개수
4. 키워드별 긍/부정 개수

### 참고자료
> ![image](https://github.com/review-mate/review-mate-be/assets/65444249/693aca2d-3d1f-4ee5-aed1-5da650a762c6)

### 특이사항
> 1. 키워드별 긍/부정 개수 부분은 <긍정 키워드 개수> 기준으로 상위 7개의 정보만 정렬해서 필요

**Comment by Kwon770** [comment]
#16 와 동일한 이슈로 구현이 완료되었으므로, 닫습니다.
