### ISSUE TITLE
Mixed-Content error (SSL) 발생

### ISSUE THREAD

**Issue by hyeonjin25** [review-mate/review-mate-be#65]
## 버그 설명
배포 후 Mixed-Content error 발생
-> **net::ERR_SSL_PROTOCOL_ERROR**

찾아본 결과 chrome에서 mixed content 차단 기능에 의해 발생되는 문제
=> [잘 정리된 링크](https://kinsta.com/blog/mixed-content-warnings/#what-causes-mixed-content-warnings)
=> [추가 링크](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)

### Mixed Content란
> 일반 텍스트 HTTP를 사용하여 가져온 콘텐츠가 포함된 HTTPS 페이지를 혼합 콘텐츠 페이지라고 합니다. 이와 같은 페이지는 부분적으로만 암호화되므로 스니퍼와 중간자 공격자가 암호화되지 않은 콘텐츠에 액세스할 수 있습니다. 그러면 페이지가 안전하지 않게 됩니다.
=> [출처](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#mixed_active_content)

## 문제 인식
=> HTTPS인 reviewmate.co.kr에서 HTTP인 api를 호출해서 문제가 생기는 것 같습니다.

## 관련 사진 첨부
<img width="904" alt="image" src="https://github.com/review-mate/review-mate-be/assets/65444249/8926f7fc-1f75-40eb-89bf-2f2420943348">
<img width="757" alt="image" src="https://github.com/review-mate/review-mate-be/assets/65444249/8b1c0335-4ab4-4634-8e4b-5d4b9e72ec97">

**Comment by Kwon770** [comment]
HTTPS지원과 Amazon ACM을 통해 SSL 등록 진행했습니다. 문제가 해결됬는지 확인해주세요.
**버그 확인 전에 변경사항 꼭 필독해주세요.**

![스크린샷 2023-10-10 18 30 57](https://github.com/review-mate/review-mate-be/assets/49567744/e9b004fc-c763-4737-97d2-c6ba7bd900f1)

![스크린샷 2023-10-10 18 31 11](https://github.com/review-mate/review-mate-be/assets/49567744/24419341-3b8a-4bae-bbc0-ac17c1592cba)



## 변경 사항

### 새 도메인
https://api.reviewmate.co.kr/
https://api.reviewmate.co.kr/swagger-ui/index.html

- 프로덕션 서버 배포: 테스트 서버가 아니라 프로덕션 서버에 적용했습니다. 기존의 테스트 서버 도메인을 본 서버 도메인으로 바꿔주세요.
- https 지원: 주소만 입력하면 자동으로 https 접속이 됩니다.
- 포트 443 지원: 더 이상 도메인 뒤에 포트 번호를 붙일 필요가 없습니다.

### 🚨 주의사항
- http 혹은 포트 8080, 80 사용하면 안됩니다.
- 기존의 test.api.reviewmate.kr 도메인은 닫혔습니다.
