### ISSUE TITLE
이미지 첨부된 리뷰 작성시 500 에러 발생

### ISSUE THREAD

**Issue by hyeonjin25** [review-mate/review-mate-be#74]
### 에러
리뷰 작성시 이미지를 함께 전송하면 500error가 발생합니다.
이미지를 추가하지 않고 전송시 잘 작동하는 것으로 보아, 이미지 관련한 문제가 있을 것으로 예상됩니다.

### 참고 자료
<img width="900" alt="image" src="https://github.com/review-mate/review-mate-be/assets/65444249/d0764f2e-bdc9-42cb-9628-14c7f1a7639d">
<img width="898" alt="image" src="https://github.com/review-mate/review-mate-be/assets/65444249/884c4c6d-9d39-494c-92cd-37248f4e4806">

**Comment by Kwon770** [comment]
`Content-type: application/json` 부분이 문제일 것 같아요. 사진과 리뷰 데이터를 동시에 받기위해 `multipart/form-data`를 사용중이고, json 정보 데이터와 사진 파일은 별도로 형식을 지정해야해요. 아래 블로그 확인해서 시도해봐주세용

https://velog.io/@horang-e/Formdata%EB%A1%9C-%EC%82%AC%EC%A7%84-%EC%9C%A0%ED%98%95%EA%B3%BC-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9C%A0%ED%98%95%EC%9D%84-%EB%8B%A4%EB%A5%B4%EA%B2%8C-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

**Comment by Kwon770** [comment]
그 외에도 S3 시크릿값 설정 오류로 보이는 문제가 있었네요. 해결했습니다. 😢

**Comment by hyeonjin25** [comment]
프론트에서도 말씀해주신 content-type 설정 완료해서 결과적으로 성공했습니다! 수고하셨습니다~~
